version: "3.9"
services:
  db:
    image: mongo
    restart: always
    networks:
      - default
    ports:
      - "27017:27017"
    container_name: mongodb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: app
    environment:
      MONGO_URI: mongodb://mongodb:27017
      DB_NAME: interview
