// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// CreateStaff provides a mock function with given fields: ctx
func (_m *AuthHandler) CreateStaff(ctx *gin.Context) {
	_m.Called(ctx)
}

// Login provides a mock function with given fields: ctx
func (_m *AuthHandler) Login(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewAuthHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthHandler(t mockConstructorTestingTNewAuthHandler) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
