// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// InterviewHandler is an autogenerated mock type for the InterviewHandler type
type InterviewHandler struct {
	mock.Mock
}

// AddInterviewComment provides a mock function with given fields: ctx
func (_m *InterviewHandler) AddInterviewComment(ctx *gin.Context) {
	_m.Called(ctx)
}

// ArchiveInterviewAppointment provides a mock function with given fields: ctx
func (_m *InterviewHandler) ArchiveInterviewAppointment(ctx *gin.Context) {
	_m.Called(ctx)
}

// CreateInterviewAppointment provides a mock function with given fields: ctx
func (_m *InterviewHandler) CreateInterviewAppointment(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetInterviewAppointment provides a mock function with given fields: ctx
func (_m *InterviewHandler) GetInterviewAppointment(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetInterviewAppointments provides a mock function with given fields: ctx
func (_m *InterviewHandler) GetInterviewAppointments(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateInterviewAppointment provides a mock function with given fields: ctx
func (_m *InterviewHandler) UpdateInterviewAppointment(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateInterviewComment provides a mock function with given fields: ctx
func (_m *InterviewHandler) UpdateInterviewComment(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewInterviewHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewInterviewHandler creates a new instance of InterviewHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInterviewHandler(t mockConstructorTestingTNewInterviewHandler) *InterviewHandler {
	mock := &InterviewHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
