// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Middlewares is an autogenerated mock type for the Middlewares type
type Middlewares struct {
	mock.Mock
}

// AdminMiddleware provides a mock function with given fields: ctx
func (_m *Middlewares) AdminMiddleware(ctx *gin.Context) {
	_m.Called(ctx)
}

// StaffMiddleware provides a mock function with given fields: ctx
func (_m *Middlewares) StaffMiddleware(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewMiddlewares interface {
	mock.TestingT
	Cleanup(func())
}

// NewMiddlewares creates a new instance of Middlewares. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMiddlewares(t mockConstructorTestingTNewMiddlewares) *Middlewares {
	mock := &Middlewares{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
